### PR TITLE
introduce GUI for Friday

### PR DESCRIPTION
**Pull request by fm-sys**

### CODE REVIEW

**Comment by fm-sys** [comment]
I had to move nearly everything around :-/ But hey, now it is working!!!

**Comment by fm-sys** [comment]
https://pypi.org/project/PyQt5/
https://pypi.org/project/PyQtWebEngine/

These two packages needs to be installed. Should we add them to the `requirements.txt`?

**Comment by fm-sys** [comment]
Some features like voice change I had to comment out. Maybe you can tackle them after merging the PR?

**Comment by fm-sys** [comment]
Btw, with this PR command line as well as gui execution is possible:

- `friday.py` -> command line
- `gui.pyw` -> graphical user interface

**Review by Krrishdhaneja — APPROVED** [review]

**Comment by Krrishdhaneja** [comment]
Man, you're just AWESOME!

**Comment by Krrishdhaneja** [comment]
> https://pypi.org/project/PyQt5/
> https://pypi.org/project/PyQtWebEngine/
> 
> These two packages needs to be installed. Should we add them to the `requirements.txt`?
> 

Ya we must

**Comment by fm-sys** [comment]
> > https://pypi.org/project/PyQt5/
> > https://pypi.org/project/PyQtWebEngine/
> > These two packages needs to be installed. Should we add them to the `requirements.txt`?
> 
> Ya we must

Can you do this? Also, why is `pyaudio` not listed there but needs to be installed in an additional step as shown at the Readme? 

And have you tested my GUI at your PC? Does everything work (except the mic button which is disabled ;-) )?

**Comment by Krrishdhaneja** [comment]
gui is good but i think the bubble must be small, can u tell me how would i do that and how is the tts working if you haven't imported `pyttsx3` ?

**Comment by Krrishdhaneja** [comment]
i changed the font size to medium cuz large was too large.

**Comment by fm-sys** [comment]
> tts working if you haven't imported `pyttsx3` ?

tts is done inside the `friday.py`, not inside `gui.py`. Therefore tts is working as it is imported there, and we import `friday.py` from `gui.py`

**Comment by Krrishdhaneja** [comment]
> 
> 
> > > https://pypi.org/project/PyQt5/
> > > https://pypi.org/project/PyQtWebEngine/
> > > These two packages needs to be installed. Should we add them to the `requirements.txt`?
> > 
> > 
> > Ya we must
> 
> Can you do this? Also, why is `pyaudio` not listed there but needs to be installed in an additional step as shown at the Readme?
> 
> And have you tested my GUI at your PC? Does everything work (except the mic button which is disabled ;-) )?

`pyaudio` is not in `requirements.txt` as there are additional steps too, like install `apt install libasound-dev` (which pip can't perform). So that is why i haven't added `pyaudio` to `requirements.txt`

**Comment by Krrishdhaneja** [comment]
hey @fm-sys I installed Pop_OS!  for testing this on vmware but was getting error when running `friday_gui.py` ->
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

**Comment by fm-sys** [comment]
No idea. But I'm not a Linux user. When I used Linux, I had to enter numerous commands into the command line until slles finally ran. Unfortunately, I can't help you. Just try another Linux distribution. For example, Linux Mint

**Comment by Krrishdhaneja** [comment]
But they all are Ubuntu based so I don't think that much difference would be there?

**Comment by Krrishdhaneja** [comment]
> No idea. But I'm not a Linux user. When I used Linux long ago, I had to enter numerous commands into the command line until all programmes finally ran. Unfortunately, I can't help you. Just try another Linux distribution. For example, Linux Mint

It finally ran fine, on Linux Mint...😁

**Pull request merged**
