### PR TITLE
remove .idea folder from and move api config to external file

### PR DESCRIPTION
**Pull request by fm-sys**
- move API config to external `api_config.txt` file which must be located in the root directory

The file should look like this: (spaces do not matter)
```
weather_api_key = xxx
wolframalpha_api_key = xxx
```

- remove .idea folder from github as it contains developer specific settings (git showed me over 100 lines of changes that are completely unimportant and only lead to merge conflicts, @Krrishdhaneja but to be safe make a copy of the .idea folder and store it outside the repo folder before pulling the changes)
- round weather temperature to 1 decimal and use correct conversion for Kelvin to Celsius

### CODE REVIEW

**Review by Krrishdhaneja — APPROVED** [review]
Nice work!

**Comment by Krrishdhaneja** [comment]
But as you can see I added that .idea folder to .gitignore but cuz sometimes I use Pycharm for this, it just gets added so that the config can be saved.

**Comment by Krrishdhaneja** [comment]
And have you copied the api keys and if yes then please tell me how to remove that from commit history.

**Comment by fm-sys** [comment]
> And have you copied the api keys and if yes then please tell me how to remove that from commit history.

Yes, I have copied them. Unfortunately, removing them it's not that easy. I think the best would to squash all old commits into one. 

See https://stackoverflow.com/questions/51211396/how-do-you-squash-old-commits-together

If you are not firm with git in the command line, I could try to do it for you if you add me as collaborator for the repository...



> But as you can see I added that .idea folder to .gitignore but cuz sometimes I use Pycharm for this, it just gets added so that the config can be saved.

I use pycharm myself. But I noticed that you need to commit the .gitignore before you create the file/folder otherwise it will be added anyway...

**Comment by fm-sys** [comment]
> If you are not firm with git in the command line, I could try to do it for you if you add me as collaborator for the repository (write access)...

If you have any uncommitted changes make sure you commit and push them. I will try to squash the old commits in a few hours. 

Please give me a notice if you are ready. 

Afterwards (probably tomorrow) you will need to force pull the new master branch... (using the cmd command `git reset --hard origin/master` in your local repository folder)

**Comment by Krrishdhaneja** [comment]
Sorry if I disturb you, but can you squash tomorrow, cuz i would be turning on my machine tomorrow as i am preparing for my exam now.

**Comment by fm-sys** [comment]
> Sorry if I disturb you, but can you squash tomorrow, cuz i would be turning on my machine tomorrow as i am preparing for my exam now.

No problem. Just tell me when you're ready

**Pull request merged**
