### PR TITLE
make travis-ci happy (part 2) ;-)

### PR DESCRIPTION
**Pull request by fm-sys**
Another try...

### CODE REVIEW

**Comment by fm-sys** [comment]
Please do not merge yet...

**Comment by Krrishdhaneja** [comment]
Umm.. @fm-sys should i end the build cuz it just stuck there?

**Comment by fm-sys** [comment]
wolframalpha Requires Python >=3.6, therefore the test is failing (https://github.com/Krrishdhaneja/Friday/pull/14/checks?check_run_id=1622725837). Please just deactivate the test as we cannot fix this.

**Comment by fm-sys** [comment]
> 
> 
> Umm.. @fm-sys should i end the build cuz it just stuck there?

They might get stuck as they are waiting for a user input... No Idea what we can do if this should be the case.

**Comment by Krrishdhaneja** [comment]
> > Umm.. @fm-sys should i end the build cuz it just stuck there?
> 
> They might get stuck as they are waiting for a user input... No Idea what we can do if this should be the case.

But in Python package action it is saying : no input from user
So, the build finished successfully?

**Comment by fm-sys** [comment]
> 
> 
> > Umm.. @fm-sys should i end the build cuz it just stuck there?
> 
> They might get stuck as they are waiting for a user input... No Idea what we can do if this should be the case.

Looks like the other ones really get stuck. But actually we don't need them, as we have the github actions tests which do exactly the same

**Comment by fm-sys** [comment]
> 
> 
> > > Umm.. @fm-sys should i end the build cuz it just stuck there?
> > 
> > 
> > They might get stuck as they are waiting for a user input... No Idea what we can do if this should be the case.
> 
> But in Python package action it is saying : no input from user
> So, the build finished successfully?

looks like

**Comment by Krrishdhaneja** [comment]
So, should i remove travis and azure ?

**Comment by fm-sys** [comment]
> So, should i remove travis and azure ?

I would vote for it. It's always hard to maintain multiple ci's...

**Comment by Krrishdhaneja** [comment]
Ok

**Comment by Krrishdhaneja** [comment]
Should i merge this now ? @fm-sys ?

**Comment by Krrishdhaneja** [comment]
@fm-sys should i merge this ?

**Comment by fm-sys** [comment]
> 
> 
> @fm-sys should i merge this ?

Yep. Ok from my side.

**Review by Krrishdhaneja — APPROVED** [review]
Awesome!

**Pull request merged**
